# Generated by Django 2.2.16 on 2020-12-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('emp_codigo', models.CharField(max_length=5)),
                ('telefone', models.CharField(max_length=13)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.Cargo')),
            ],
        ),
    ]
